### ISSUE TITLE
_ak - FanDuel 

### ISSUE THREAD

**Issue by fudgemasterultra** [jimtheflash/betfinder#29]
Hey, I noticed you also are having an issue finding out what _ak is. I'm trying to get that figured out as well. I've been using burp suite to intercept packets to FanDuel to see if they ever give it to us, but no luck just yet.  If I see anything I'll make another post with information on it, and likewise, if you find anything out please let me know. It looks like the _ak doesn't expire quickly I used the one you provided which looked to be a few days old, and it still worked.

**Comment by jimtheflash** [comment]
Thanks for the note! I don't know if I've ever actually changed this parameter to be honest - so you may end up being in the clear! It looks like it uses the same value across devices and users too.

**Comment by jimtheflash** [comment]
tidying up issues
