### ISSUE TITLE
NFL Draft Props

### ISSUE THREAD

**Issue by KentWeyrauch** [jimtheflash/betfinder#30]
Hey Jim. Great work on this repo! This isn't a real issue, but I was wondering if I could get a hand transfiguring some of this code to pull NFL Draft props from FanDuel. I have DK working just fine. And if you have any insight to other books too, that would be cool but not needed. I haven't even tried them yet. Thanks!

**Comment by jimtheflash** [comment]
Thanks for your note! It looks like the NFL props on FD are living in a json that you can get by calling this URL:
`https://sbapi.il.sportsbook.fanduel.com/api/competition-page?betexRegion=GBR&capiJurisdiction=intl&currencyCode=USD&exchangeLocale=en_US&includeBadges=true&includeLayout=true&includePrices=true&language=en&regionCode=NAMERICA&_ak=FhMFpcPWXMeyZxOx&eventTypeId=6423&competitionId=11212658&includeStaticCards=false`

You can pull that directly into `R` using `jsonlite::fromJSON('that_long_url')` which will give you a list object; the specific odds live in the `attachments > markets` element of that list, and then it should be parseable from there.

I don't think I'm going to have any time to try and update the package to accommodate this yet - the `tidyup` phase of `get_props` would be pretty beat without a good lookup of nfl/draft pick names - but i definitely want to add more futures to this setup at some point.

**Comment by KentWeyrauch** [comment]
This got me there, thank you so much. For my own knowledge, how did you find/isolate the competitionId?
