### ISSUE TITLE
Caesar's Sportsbook Issue

### ISSUE THREAD

**Issue by mjshanno** [jimtheflash/betfinder#31]
Hey Jim. Thanks so much for putting this together. I'm learning a lot.

It looks like the Caesar's sportsbook pull isn't working anymore. I tried tinkering with different ways to get the data from api.americanwagering.com, but can't seem to GET it. I wonder if something has changed with access issues. Are you seeing the same issue? Thanks

**Comment by jimtheflash** [comment]
Yep, there's definitely a bug going on with pulling data from Caesar's, looks like they made some changes that probably will require us to go a different route. I'll try to take a look this month, but I'm guessing we'll have to either check to see if their app is easier to scrape, or go the selenium route like we do with mgm. The same thing is probably going on with BetRivers fwiw.

**Comment by jimtheflash** [comment]
ah this was wayyyy easier than i thought, caesars is up and running again for first player to score. i haven't sorted out why, but sometimes `jsonlite::fromJSON(url)` works when `httr::GET(url)` doesn't, and it's probably something related to the header strings, but i'm not sure what atm.

either way, closing this issue, thanks for the note!
